/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#0e1511",
        "on-secondary-container": "#afb6bd",
        "secondary": "#c1c7cf",
        "surface-container-lowest": "#09100c",
        "on-background": "#dde4dd",
        "tertiary-fixed": "#d3e4fe",
        "error": "#ffb4ab",
        "outline": "#86948a",
        "on-tertiary-fixed-variant": "#38485d",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary-container": "#2a3a4f",
        "on-secondary-fixed-variant": "#41474e",
        "inverse-surface": "#dde4dd",
        "outline-variant": "#3c4a42",
        "on-primary": "#003824",
        "on-secondary": "#2b3137",
        "on-surface": "#dde4dd",
        "surface-container-highest": "#2f3632",
        "on-tertiary": "#213145",
        "secondary-fixed": "#dde3eb",
        "surface-container-high": "#242c27",
        "surface-container-low": "#161d19",
        "surface": "#0e1511",
        "primary": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#c1c7cf",
        "error-container": "#93000a",
        "surface-variant": "#2f3632",
        "surface-dim": "#0e1511",
        "on-secondary-fixed": "#161c22",
        "primary-container": "#10b981",
        "surface-bright": "#343b36",
        "secondary-container": "#41474e",
        "inverse-on-surface": "#2b322d",
        "on-tertiary-fixed": "#0b1c30",
        "inverse-primary": "#006c49",
        "tertiary": "#b7c8e1",
        "tertiary-container": "#94a4bd",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-surface-variant": "#bbcabf",
        "surface-tint": "#4edea3",
        "surface-container": "#1a211d",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "primary-fixed-dim": "#4edea3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "64px",
        "gutter": "24px",
        "base": "4px",
        "sm": "16px",
        "md": "24px",
        "xs": "8px",
        "lg": "40px",
        "container-max": "1200px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Outfit"],
        "display-lg": ["Outfit"],
        "label-md": ["Inter"],
        "headline-md": ["Outfit"],
        "headline-lg": ["Outfit"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
